# Generated by Django 4.0.4 on 2022-04-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_recurso_alter_servico_icone'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='icone',
            field=models.CharField(choices=[('lni-cog', 'Engrenagem'), ('lni-stats-up', 'Gráfico'), ('lni-users', 'Usuários'), ('lni-layers', 'Design'), ('lni-mobile', 'Mobile'), ('lni-rocket', 'Foguete'), ('lni-laptop-phone', 'Computador/celular'), ('lni-leaf', 'Folha')], default='#', max_length=16, verbose_name='Icone'),
        ),
    ]
